CREATE PROCEDURE [dbo].[usp_ApproveShop]
	@ShopId UNIQUEIDENTIFIER,
	@RowsAffected INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION;

		UPDATE SHOPS
		SET system_status = 'approved', 
			updated_at = GETUTCDATE()
		WHERE id = @ShopId

		SET @RowsAffected = @@ROWCOUNT;

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		THROW;
	END CATCH
END
