CREATE TABLE [dbo].[CARTS] (
    [Id]         UNIQUEIDENTIFIER   DEFAULT (newsequentialid()) NOT NULL,
    [UserId]     UNIQUEIDENTIFIER   NOT NULL,
    [created_at] DATETIMEOFFSET (7) NOT NULL,
    [update_at]  DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_CARTS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CARTS_USERS_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USERS] ([id])
);




GO
CREATE NONCLUSTERED INDEX [IX_CARTS_UserId]
    ON [dbo].[CARTS]([UserId] ASC);

