CREATE TABLE [dbo].[CART_ITEMS] (
    [Id]        UNIQUEIDENTIFIER   NOT NULL,
    [CartId]    UNIQUEIDENTIFIER   NOT NULL,
    [VariantId] UNIQUEIDENTIFIER   NOT NULL,
    [Quantity]  INT                DEFAULT ((1)) NOT NULL,
    [CreatedAt] DATETIMEOFFSET (7) NOT NULL,
    [UpdatedAt] DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_CART_ITEMS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CART_ITEMS_CARTS_CartId] FOREIGN KEY ([CartId]) REFERENCES [dbo].[CARTS] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_CART_ITEMS_VARIANTS_VariantId] FOREIGN KEY ([VariantId]) REFERENCES [dbo].[VARIANTS] ([id])
);


GO
CREATE NONCLUSTERED INDEX [IX_CART_ITEMS_VariantId]
    ON [dbo].[CART_ITEMS]([VariantId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CART_ITEMS_CartId]
    ON [dbo].[CART_ITEMS]([CartId] ASC);

