CREATE TABLE [dbo].[INVOICE_ITEMS] (
    [Id]              UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
    [InvoiceId]       UNIQUEIDENTIFIER NOT NULL,
    [ProductId]       UNIQUEIDENTIFIER NOT NULL,
    [VariantId]       UNIQUEIDENTIFIER NOT NULL,
    [Quantity]        INT              NOT NULL,
    [PriceAtPurchase] DECIMAL (18, 2)  NOT NULL,
    CONSTRAINT [PK_INVOICE_ITEMS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_INVOICE_ITEMS_INVOICES_InvoiceId] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[INVOICES] ([id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEMS_VariantId]
    ON [dbo].[INVOICE_ITEMS]([VariantId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEMS_ProductId]
    ON [dbo].[INVOICE_ITEMS]([ProductId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_ITEMS_InvoiceId]
    ON [dbo].[INVOICE_ITEMS]([InvoiceId] ASC);

