CREATE TABLE [dbo].[INVOICE_APPLIED_COUPONS] (
    [id]              UNIQUEIDENTIFIER   DEFAULT (newsequentialid()) NOT NULL,
    [invoice_id]      UNIQUEIDENTIFIER   NOT NULL,
    [coupon_id]       UNIQUEIDENTIFIER   NOT NULL,
    [discount_amount] DECIMAL (18, 2)    NOT NULL,
    [applied_at]      DATETIMEOFFSET (7) DEFAULT (getutcdate()) NOT NULL,
    [InvoiceId1]      UNIQUEIDENTIFIER   NULL,
    CONSTRAINT [PK_INVOICE_APPLIED_COUPONS] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_INVOICE_APPLIED_COUPONS_COUPONS_coupon_id] FOREIGN KEY ([coupon_id]) REFERENCES [dbo].[COUPONS] ([id]) ON DELETE CASCADE,
    CONSTRAINT [FK_INVOICE_APPLIED_COUPONS_INVOICES_invoice_id] FOREIGN KEY ([invoice_id]) REFERENCES [dbo].[INVOICES] ([id]) ON DELETE CASCADE,
    CONSTRAINT [FK_INVOICE_APPLIED_COUPONS_INVOICES_InvoiceId1] FOREIGN KEY ([InvoiceId1]) REFERENCES [dbo].[INVOICES] ([id])
);




GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_APPLIED_COUPONS_invoice_id]
    ON [dbo].[INVOICE_APPLIED_COUPONS]([invoice_id] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_INVOICE_APPLIED_COUPONS_coupon_id]
    ON [dbo].[INVOICE_APPLIED_COUPONS]([coupon_id] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_INVOICE_APPLIED_COUPONS_InvoiceId1]
    ON [dbo].[INVOICE_APPLIED_COUPONS]([InvoiceId1] ASC) WHERE ([InvoiceId1] IS NOT NULL);

