CREATE TABLE [dbo].[PRODUCT_DETAILS] (
    [ProductId]        UNIQUEIDENTIFIER NOT NULL,
    [summary]          NVARCHAR (500)   NULL,
    [description_html] NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_PRODUCT_DETAILS] PRIMARY KEY CLUSTERED ([ProductId] ASC),
    CONSTRAINT [FK_PRODUCT_DETAILS_PRODUCTS_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[PRODUCTS] ([id]) ON DELETE CASCADE
);

