CREATE TABLE [dbo].[USER_EXTERNAL_LOGINS] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [Provider]    NVARCHAR (450)   NOT NULL,
    [ProviderKey] NVARCHAR (MAX)   NOT NULL,
    CONSTRAINT [PK_USER_EXTERNAL_LOGINS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_USER_EXTERNAL_LOGINS_USERS_Id] FOREIGN KEY ([Id]) REFERENCES [dbo].[USERS] ([id]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_USER_EXTERNAL_LOGINS_Provider_Id]
    ON [dbo].[USER_EXTERNAL_LOGINS]([Provider] ASC, [Id] ASC);

