CREATE TABLE [dbo].[USER_SAVED_COUPONS] (
    [id]           UNIQUEIDENTIFIER   DEFAULT (newsequentialid()) NOT NULL,
    [user_id]      UNIQUEIDENTIFIER   NOT NULL,
    [coupon_id]    UNIQUEIDENTIFIER   NOT NULL,
    [is_used]      BIT                NOT NULL,
    [saved_at]     DATETIMEOFFSET (7) NOT NULL,
    [last_used_at] DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_USER_SAVED_COUPONS] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_USER_SAVED_COUPONS_COUPONS_coupon_id] FOREIGN KEY ([coupon_id]) REFERENCES [dbo].[COUPONS] ([id]) ON DELETE CASCADE,
    CONSTRAINT [FK_USER_SAVED_COUPONS_USERS_user_id] FOREIGN KEY ([user_id]) REFERENCES [dbo].[USERS] ([id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_USER_SAVED_COUPONS_user_id]
    ON [dbo].[USER_SAVED_COUPONS]([user_id] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_USER_SAVED_COUPONS_coupon_id]
    ON [dbo].[USER_SAVED_COUPONS]([coupon_id] ASC);

